#!/bin/sh
HURON_DIR=/www/huron

cd $HURON_DIR
python -m venv venv --system-site-packages
source $HURON_DIR/venv/bin/activate
$HURON_DIR/venv/bin/pip install  --no-index -r requirements.txt
$HURON_DIR/venv/bin/pip install --no-index $HURON_DIR 
export FLASK_APP=huron
$HURON_DIR/venv/bin/python $HURON_DIR/manage.py createdb

rm /etc/init.d/S55initial
