#! /bin/sh
APPNAME=huron
USER=root
PATH=/bin:/usr/bin:/sbin:/usr/sbin
APPMODULE=$APPNAME.wsgi:app
DAEMON=gunicorn
BIND=127.0.0.1:8000
PIDFILE=/var/run/gunicorn.pid
LOGFILE=/var/log/$DAEMON.log
WORKERS=2

case "$1" in
start)
	$DAEMON --daemon --bind=$BIND --pid=$PIDFILE --workers=$WORKERS --log-file=$LOGFILE --reload $APPMODULE
	;;
stop)
	kill -n 9 "$(cat "$PIDFILE")"
	;;
force-reload | restart)
	$0 stop
	$0 start
	;;
status)
	status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
	;;
*)
	echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
