#! /bin/sh
APPNAME=victoria
USER=root
PATH=/bin:/usr/bin:/sbin:/usr/sbin
APPMODULE=$APPNAME
PIDFILE=/var/run/$APPNAME.pid
LOGFILE=/var/log/$APPNAME.log
WORKERS=2

case "$1" in
  start)
        python -m $APPNAME --logfile $LOGFILE --pid $PIDFILE
    ;;
  stop)
        killproc -p $PIDFILE $APPNAME
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $APPNAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
