#! /bin/sh
APPNAME=erie
USER=root
PATH=/bin:/usr/bin:/sbin:/usr/sbin
APPMODULE=$APPNAME
PIDFILE=/var/run/$APPNAME.pid
LOGFILE=/var/log/$APPNAME.log
CONFIGFILE=/etc/sprtch.yaml

case "$1" in
start)
	python -m $APPMODULE --logfile $LOGFILE --pid $PIDFILE --config $CONFIGFILE
	;;
stop)
	kill -n 9 "$(cat "$PIDFILE")"
	;;
force-reload | restart)
	$0 stop
	$0 start
	;;
status)
	status_of_proc -p $PIDFILE $APPMODULE && exit 0 || exit $?
	;;
*)
	echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
